name: Build, Package, and Release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner

    steps:
      # Step 1: Checkout code from GitHub repository
      - uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Step 4: Build executable using PyInstaller and .spec file
      - name: Build executable
        run: |
          pyinstaller SportScrapper.spec  # Use the .spec file to bundle the necessary modules

      # Step 5: Install Inno Setup (pre-installed on Windows runner) and create installer
      - name: Create installer
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" SportScrapper.iss /O"release\installer"

      # Step 6: Create a new Git tag (versioning)
      - name: Create a new tag
        id: tag
        run: |
          git tag v1.0.${{ github.run_number }}
          git push origin v1.0.${{ github.run_number }}

      # Step 7: Upload the installer to the release
      - name: Upload installer artifact
        uses: actions/upload-artifact@v3
        with:
          name: SportScrapper-installer
          path: release/installer/SportScrapperSetup.exe

      # Step 8: Create a new release on GitHub
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          files: release/installer/SportScrapperSetup.exe
        env:
          GITHUB_TOKEN: ${{ secrets.SS_TOKEN }}