name: Build, Package, and Release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from GitHub repository
      - uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install pyinstaller certifi pymongo PyQt5 selenium

      # Step 4: Build executable using PyInstaller
      - name: Build executable
        run: |
          pyinstaller --name SportScrapper --onefile --windowed --icon=assets/icon.png --add-data "assets:assets" --add-data "logs:logs" src/main.py

      # Step 5: Install Inno Setup Compiler (for creating installer)
      - name: Install Inno Setup
        run: |
          sudo apt-get update
          sudo apt-get install -y innosetup

      # Step 6: Create the installer using Inno Setup
      - name: Create installer
        run: |
          innosetup-compiler /path/to/your/installer.iss

      # Step 7: Create a new Git tag if it does not already exist
      - name: Create a new tag
        id: tag
        run: |
          git fetch --tags
          if [ -z "$(git tag -l v1.0.${{ github.run_number }})" ]; then
            git tag v1.0.${{ github.run_number }}
            git push origin v1.0.${{ github.run_number }}
          fi

      # Step 8: Upload the installer to the release
      - name: Upload installer artifact
        uses: actions/upload-artifact@v3
        with:
          name: SportScrapper-installer
          path: path/to/your/installer/output/SportScrapperSetup.exe  # Update with your actual path

      # Step 9: Create a new release on GitHub and upload the installer
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          files: path/to/your/installer/output/SportScrapperSetup.exe  # Ensure the .exe installer is uploaded
        env:
          GITHUB_TOKEN: ${{ secrets.SS_TOKEN }}